return {
 ["Fira Mono Bold#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Bold.otf", false },
 ["Fira Mono#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["Fira Sans Italic#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Italic.otf", false },
 ["Fira Sans Light Italic#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["Fira Sans Light#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["Fira Sans#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Regular.otf", false },
 ["FiraMono/BI:mode=base;script=latn;language=dflt;#bi#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-BoldOblique.otf", false },
 ["FiraMono/BI:mode=base;script=latn;language=dflt;#bi#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-BoldOblique.otf", false },
 ["FiraMono/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-BoldOblique.otf", false },
 ["FiraMono/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-BoldOblique.otf", false },
 ["FiraMono/I:mode=base;script=latn;language=dflt;#i#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Oblique.otf", false },
 ["FiraMono/I:mode=base;script=latn;language=dflt;#i#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Oblique.otf", false },
 ["FiraMono/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Oblique.otf", false },
 ["FiraMono/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Oblique.otf", false },
 ["FiraMono:mode=base;#717617"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=base;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=base;script=latn;language=dflt;#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=base;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;#717617"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;script=latn;language=dflt;#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMonoMedium/I:mode=base;script=latn;language=dflt;#i#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium:mode=base;script=latn;language=dflt;#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium:mode=base;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium:mode=node;script=latn;language=dflt;#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraSans:mode=base;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Regular.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Regular.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;#552140"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Regular.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;#662568"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Regular.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;#795081"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Regular.otf", false },
 ["FiraSansItalic:mode=base;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Italic.otf", false },
 ["FiraSansItalic:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Italic.otf", false },
 ["FiraSansLight:mode=base;#717617"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=base;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=base;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;#717617"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#222548"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#333822"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#445096"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#556370"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#609224"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#667644"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#801172"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLightItalic:mode=base;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
}