github.com:
    users:
        KucherovaViktoria:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: KucherovaViktoria
